# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://christophschnabl.github.io"
# Language used
languageCode = "en-us"
# Website title
title = "Christoph Schnabl"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)

# Configure permalinks style
[permalinks]
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = "My homepage"
    # Author of the site
    authorName = "Christoph Schnabl"
    # Main image for the author. This will be the default image for SEO.
    #[params.imgname]
        #name = "img/main.jpg"
        # Add an alt description for the image
        #alt = "Profile picture"

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "scholar.social"

    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    webmention = "schnabl.xyz"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
